apiVersion: v1

kind: PersistentVolume

metadata:
  name: model-pv

spec:
  capacity:
    storage: {{ .Values.persistence.size }}

  accessModes:
    - ReadWriteMany

  hostPath:
    path: "/mnt/data"

