FROM python:3.10

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY src/training /app/training
COPY src/data /app/data
COPY src/models /app/models

CMD ["python", "training/train.py"]

